apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"

jobs:
  build-deploy:
    steps:
      - name: Deploy Using CBCI
        uses: cloudbees-io/jenkins-run-job
        with:
          url: https://releaseiq.ironman.releaseiq.io/
          username: ${{ secrets.CBCI_IRONMAN_USERNAME }}
          password: ${{ secrets.CBCI_IRONMAN_PASSWORD }}
          job-name: demo_build_component2
          parameters: '{"TAG_NAME":"${{ cloudbees.scm.sha }}"}'
      - name: ConfigureAWSCredentials
        uses: cloudbees-io/configure-aws-credentials@v0.0.4
        with:
          aws-access-key-id: ${{ secrets.RIQ_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.RIQ_SECRET_KEY }}
          aws-region: us-west-2
      - id: kubeconfig-context-update
        name: kubeconfig-context-update
        uses: docker://amazon/aws-cli
        run: |
          aws eks update-kubeconfig --region us-west-2 --name riq-prod-cluster01
      - id: install-chart
        name: Install reports-service helm chart
        uses: cloudbees-io/helm-install
        with:
          chart-location: .deployment/
          version: 0.0.1
          release-name: demo-component2
          namespace: saas-demo
          values: |
            image:
              repository: 641518622681.dkr.ecr.us-west-2.amazonaws.com/demo_component2
              tag: ${{ cloudbees.scm.sha }}
