apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"

jobs:
  build-deploy:
    steps:
      - name: Deploy Using CBCI
        uses: cloudbees-io/cbci-run-job
        with:
          url: https://releaseiq.ironman.releaseiq.io/
          username: ${{ secrets.CBCI_IRONMAN_USERNAME }}
          password: ${{ secrets.CBCI_IRONMAN_PASSWORD }}
          job-name: demo_build_component2
          parameters: '{"TAG_NAME":"${{ cloudbees.scm.sha }}"}'
      - id: write-kubeconfig
        name: Write kubeconfig
        uses: docker://alpine:3.18
        run: |
          mkdir -p ${HOME}/.kube
          echo -e "${{ secrets.RIQ_KUBECONFIG }}" > ${HOME}/.kube/config
      - id: install-chart
        name: Install reports-service helm chart
        uses: cloudbees-io/helm-install
        with:
          chart-location: deployment
          version: 0.0.1
          release-name: demo-component2
          namespace: saas-demo
          values: |
            image:
              repository: 641518622681.dkr.ecr.us-west-2.amazonaws.com/demo_component2
              tag: ${{ cloudbees.scm.sha }}