apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"

jobs:
  build-deploy:
    environment: stage
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1.0.2
      - name: Running Snyk SCA scan
        uses: cloudbees-io/snyk-sca-scan-dependency@v1
        with:
          orgname: ${{ vars.SNYK_SAAS_ORG_NAME }}
          token: ${{ secrets.SNYK_SAAS_TOKEN }}
          language: "LANGUAGE_JAVA"
          
      - name: Running Snyk SAST Scan
        uses: cloudbees-io/snyk-sast-scan-code@v1
        with:
          orgname: ${{ vars.SNYK_SAAS_ORG_NAME }}
          token: ${{ secrets.SNYK_SAAS_TOKEN }}
          language: "LANGUAGE_JAVA"

      - name: Maven Build
        uses: docker://maven:3.8.7-openjdk-18-slim
        run: |
          mvn clean install
          ls -lrt target/

      - name: Build Using CBCI
        uses: cloudbees-io/jenkins-run-job
        kind: build
        with:
          url: https://releaseiq.ironman.releaseiq.io/
          username: ${{ secrets.CBCI_IRONMAN_USERNAME }}
          token: ${{ secrets.CBCI_IRONMAN_PASSWORD }}
          job-name: demo_build_component2
          parameters: '{"TAG_NAME":"${{ cloudbees.scm.sha }}"}'

      - name: ConfigureAWSCredentials
        uses: cloudbees-io/configure-aws-credentials@v0.0.4
        with:
          aws-access-key-id: ${{ secrets.RIQ_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.RIQ_SECRET_KEY }}
          aws-region: us-west-2

      - name: Running container scan using Trivy
        uses: cloudbees-io/trivy-scan-container@v1
        with:
          image-location: 641518622681.dkr.ecr.us-west-2.amazonaws.com/demo_component2
          image-tag: ${{ cloudbees.scm.sha }}

      - id: kubeconfig-context-update
        name: kubeconfig-context-update
        uses: docker://amazon/aws-cli
        run: |
          aws eks update-kubeconfig --region us-west-2 --name riq-prod-cluster01
      - id: install-chart
        name: Install reports-service helm chart
        uses: cloudbees-io/helm-install
        kind: deploy
        with:
          chart-location: ${{ cloudbees.workspace }}/deployment/
          version: 0.1.0
          release-name: demo-component2
          namespace: saas-demo
          values: |
            image:
              repository: 641518622681.dkr.ecr.us-west-2.amazonaws.com/demo_component2
              tag: ${{ cloudbees.scm.sha }}


